version: "3"
services:
  web:
    extends:
      file: docker/server.yml
      service: web
    restart: always
    depends_on:
      - db
    networks:
      - bcloud-network-staging
    ports:
      - 9000:9000

  nginx:
    extends:
      file: docker/server.yml
      service: nginx
    restart: always
    links:
      - web
    networks:
      - bcloud-network-staging
    ports:
      - 8001:80

  db:
    extends:
      file: docker/database.yml
      service: db
    restart: always
    networks:
      - bcloud-network-staging

  adminer:
    extends:
      file: docker/database.yml
      service: adminer
    restart: always
    networks:
      - bcloud-network-staging
    ports:
      - 8201:8080

  redis:
    image: "redis:alpine"
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - "stagingredis:/data"
    networks:
      - bcloud-network-staging
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  elastic:
    extends:
      file: docker/elastic.yml
      service: elasticsearch
    restart: always
    networks:
      - bcloud-network-staging

  # kibana:
  #   extends:
  #     file: docker/elastic.yml
  #     service: kibana
  #   restart: always
  #   networks:
  #     - bcloud-network-staging
  #   depends_on:
  #     - elastic
  #   ports:
  #     - "9010:5601"

  lilypond:
    extends:
      file: docker/addons.yml
      service: lilypond
    restart: always
    networks:
      - bcloud-network-staging

networks:
  bcloud-network-staging:

volumes:
  stagingredis:
    driver: local
