version: "3"
services:
  lilypond:
    build:
      context: ./setup/lilypond
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./data/lilypond:/scoresl
    expose:
      - 8080

  cron:
    build:
      context: ./setup/cron
      dockerfile: Dockerfile
    volumes:
      - ./logs:/var/log
  # php-queue:
  #   build:
  #     context: ./setup/php-base
  #     dockerfile: Dockerfile
  #   command: php artisan queue:work --tries=3 --timeout=90
  #   volumes:
  #     - "..:/var/www/html"
