version: "3"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    command:
      - "mysqld"
      - "--innodb_buffer_pool_size=500M"

  adminer:
    image: adminer
