version: "3"
services:
  elasticsearch:
    build:
      context: ./setup/elastic
      dockerfile: Dockerfile
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
    expose:
      - 9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
  # cerebro:
  #   image: yannart/cerebro:0.8.1
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - elasticsearch