version: "3"
services:
  web:
    build:
      context: ./setup/fpm
      dockerfile: Dockerfile
    volumes:
      - "..:/var/www/html"
      # this causes node_modules to be ignored from mount
      - "/var/www/html/node_modules"
      - "/var/www/html/vendor"
    dns:
      - 8.8.8.8
      - 4.4.4.4

  nginx:
    image: "nginx:1.17.3"
    volumes:
      - "..:/var/www/html"
      - "/var/www/html/node_modules"
      - "/var/www/html/vendor"
      - "./config/nginx:/etc/nginx/conf.d"
      - "./logs/nginx:/var/log/nginx"

  web.local:
    build:
      # change 8.0. to 8.1
      context: ./setup/php-local-8.0-future
      dockerfile: Dockerfile
      args:
        WWWGROUP: "1000"
    image: sail-8.0/app
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
    volumes:
      - "..:/var/www/html"
